package entity;


/**
 * Category generated by hbm2java
 */
public class Category {


     private String code;
     private String name;

    public Category() {
    }

	
    public Category(String code) {
        this.code = code;
    }
    public Category(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


