package entity;

/**
 * Customers generated by hbm2java
 */
public class Customers{


     private String username;
     private String password;
     private String hoten;
     private String email;
     private Boolean role;
     private Boolean gioitinh;

    public Customers() {
    }

	
    public Customers(String username) {
        this.username = username;
    }
    public Customers(String username, String password, String hoten, String email, Boolean role, Boolean gioitinh) {
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.email = email;
       this.role = role;
       this.gioitinh = gioitinh;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }
    public Boolean getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Boolean gioitinh) {
        this.gioitinh = gioitinh;
    }




}


