package entity;



/**
 * Products generated by hbm2java
 */
public class Products{

     private String code;
     private String name;
     private Double price;
     private String images;
     private String detail;

    public Products() {
    }

    public Products(String code) {
        this.code = code;
    }
    public Products(String code, String name, Double price, String images, String detail) {
       this.code = code;
       this.name = name;
       this.price = price;
       this.images = images;
       this.detail = detail;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }




}


